// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WattTime.Agent.Services.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BalancingAuthority
    {
        /// <summary>
        /// Initializes a new instance of the BalancingAuthority class.
        /// </summary>
        public BalancingAuthority()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BalancingAuthority class.
        /// </summary>
        public BalancingAuthority(int? id = default(int?), string abbrev = default(string), string name = default(string))
        {
            Id = id;
            Abbrev = abbrev;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "abbrev")]
        public string Abbrev { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
