// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WattTime.Agent.Services.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Data
    {
        /// <summary>
        /// Initializes a new instance of the Data class.
        /// </summary>
        public Data()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Data class.
        /// </summary>
        /// <param name="datatype">Possible values include: 'MOER',
        /// 'GENERATION', 'EXPORT', 'IMPORT', 'GEN_RENEW', 'LOAD', 'LMP',
        /// 'LMP_ENE', 'LMP_LOSS', 'LMP_CONG', 'LMP_GHG', 'TEMP_C'</param>
        public Data(System.DateTime? pointTime = default(System.DateTime?), double? value = default(double?), double? frequency = default(double?), string market = default(string), string ba = default(string), string datatype = default(string))
        {
            PointTime = pointTime;
            Value = value;
            Frequency = frequency;
            Market = market;
            Ba = ba;
            Datatype = datatype;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "point_time")]
        public System.DateTime? PointTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "frequency")]
        public double? Frequency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "market")]
        public string Market { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ba")]
        public string Ba { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'MOER', 'GENERATION',
        /// 'EXPORT', 'IMPORT', 'GEN_RENEW', 'LOAD', 'LMP', 'LMP_ENE',
        /// 'LMP_LOSS', 'LMP_CONG', 'LMP_GHG', 'TEMP_C'
        /// </summary>
        [JsonProperty(PropertyName = "datatype")]
        public string Datatype { get; set; }

    }
}
